questions = [
    {"Qu":"\n1. what is the primary goal of generative ai?","Op":["\nA) to categorize and label existing data\nB) to create new, original content by learning from existing data patterns\nC) to perform complex mathematical calculations faster than a calculator\nD) to strictly automate repetitive physical tasks on assembly lines\n"],"An":"B"},
    {"Qu":"2. What does the acronym LLM stand for in the context of Generative AI?","Op":["\nA) Local Logic Model\nB) Linked Learning Machine\nC) Large Language Model\nD) Logical Learning Module\n"],"An":"C"},
    {"Qu":"3. Which neural network architecture is widely used as the foundation for modern Large Language Models?","Op":["\nA) Convolutional Neural Network (CNN)\nB) Recurrent Neural Network (RNN)\nC) Deep Belief Network\nD) Transformer\n"],"An":"D"},
    {"Qu":"4. What is a \"hallucination\" in the context of Generative AI?","Op":["\nA) A model error that completely crashes the system\nB) A highly advanced, sentient thought process developed by the AI\nC) A confident, realistic, but factually incorrect output generated by an AI\nD) The graphical user interface used to interact with the model\n"],"An":"C"},
    {"Qu":"5. In a Generative Adversarial Network (GAN), what is the role of the discriminator?","Op":["\nA) To produce realistic fake data\nB) To analyze data and distinguish between real data and AI-generated data\nC) To process sequential audio and video data\nD) To translate natural language into programming code\n"],"An":"B"},
    {"Qu":"6. Which of the following is commonly used to generate new, high-quality images from textual descriptions?","Op":["\nA) Diffusion Models\nB) Latent Dirichlet Allocation (LDA)\nC) K-Means Clustering\nD) Random Forest\n"],"An":"A"},
    {"Qu":"7. In text generation, what does increasing the \"temperature\" parameter typically do?","Op":["\nA) It makes the output more deterministic and predictable\nB) It increases the RAM usage of the model\nC) It makes the generated text more random and creative\nD) It speeds up the tokenization process\n"],"An":"C"},
    {"Qu":"8. What does \"Tokenization\" refer to in Natural Language Processing (NLP)?","Op":["\nA) Encrypting text for secure transmission\nB) The process of splitting raw text into smaller, distinct units or words (tokens)\nC) Rewarding the model with virtual tokens during training\nD) Compressing model parameters to fit on mobile devices\n"],"An":"B"},
    {"Qu":"9. What is \"Zero-shot learning\" in Generative AI?","Op":["\nA) Training a model without using any training data at all\nB) A technique where the model completes a task without requiring any prior examples or specific training for that task\nC) The process of completely wiping a model's learned weights\nD) An evaluation method where the model is tested only on what it failed to learn\n"],"An":"B"},
    {"Qu":"10. What does RLHF (Reinforcement Learning from Human Feedback) primarily aim to achieve?","Op":["\nA) To make models faster at loading web pages\nB) To compress the physical size of AI models\nC) To align the AI's behavior and responses with human preferences and safety guidelines\nD) To teach the AI how to natively write new code\n"],"An":"C"}]
score=0
Correct=0
Wrong=0
Options="ABCD"
for q in questions:
    print(q["Qu"])
    for o in q["Op"]:
        print(o)
    while True:
        user=input("Enter you answer :-").upper()

        if user in Options:
            break
        print("Give input in Only A,B,C,D")
                
    if user==q["An"]:
        print("Correct")
        Correct+=1
        score+=1

    else:
        print("Wrong")
        Wrong+=1
        print("Answer =", q["An"])
            
print(f"Your score is {score}/{len(questions)} and your percentage is {(score/len(questions))*100:.2f}%")
print(f"Correct ={Correct}\nWrong={Wrong}")